import { AuthProvider } from '@/lib/auth-provider';
import './globals.css';
import { Inter } from 'next/font/google';

import { ThemeProvider } from '@/lib/theme-provider';
import { Toaster } from '@/components/ui/toaster';

import MainNav from '@/components/shared/main-nav';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <AuthProvider>
        <body className={inter.className}>
          <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
            <MainNav />
            {children}
            <Toaster />
          </ThemeProvider>
        </body>
      </AuthProvider>
    </html>
  );
}
